# Generated by Django 5.2.3 on 2025-07-01 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurantbranch',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='restaurants.district'),
        ),
        migrations.AddField(
            model_name='restaurantbranch',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='moreinfo',
            name='restaurant_branch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='restaurants.restaurantbranch'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='restaurant_branch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='restaurants.restaurantbranch'),
        ),
        migrations.AddField(
            model_name='restaurantschedule',
            name='restaurant_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='restaurants.restaurantbranch'),
        ),
        migrations.AlterUniqueTogether(
            name='restaurantschedule',
            unique_together={('restaurant_branch', 'day')},
        ),
    ]
