# Generated by Django 5.2.3 on 2025-07-07 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurantoutlet',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_outlets', to='restaurants.district'),
        ),
        migrations.AddField(
            model_name='restaurantoutlet',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlets', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='outletschedule',
            name='restaurant_outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='restaurants.restaurantoutlet'),
        ),
        migrations.AddField(
            model_name='moreinfo',
            name='restaurant_outlet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='restaurants.restaurantoutlet'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='restaurant_outlet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='restaurants.restaurantoutlet'),
        ),
        migrations.AlterUniqueTogether(
            name='outletschedule',
            unique_together={('restaurant_outlet', 'day')},
        ),
    ]
