# Generated by Django 5.2.3 on 2025-07-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantoutlet',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
