# Generated by Django 5.2.3 on 2025-07-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurantoutlet_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='moreinfo',
            name='delivery_time_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moreinfo',
            name='delivery_time_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
