# Generated by Django 5.2.3 on 2025-07-24 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_moreinfo_delivery_time_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moreinfo',
            name='delivery_time',
        ),
    ]
